extends Node

# Player Turret Data
var PLAYER_BULLET_EXPLOSION_DAMAGE = 2
var PLAYER_BULLET_EXPLOSION_DAMAGE_COST = 500
var PLAYER_BULLET_EXPLOSION_SIZE = 1.5	# Maximum times larger than original explosion can be
var PLAYER_BULLET_EXPLOSION_SIZE_COST = 1000	# Maximum times larger than original explosion can be
var PLAYER_BULLET_SPEED = 1000			# Pixels per second
var PLAYER_BULLET_COLOR = Color(2, 2, 2)
var PLAYER_MAX_HP = 20
var PLAYER_MAX_HP_COST = 200

# Laser Turret Data
var TURRET_LASER_COUNT = 0
var TURRET_LASER_COUNT_COST = 2000
var TURRET_LASER_BULLET_COLOR = Color(0, 1.3, 0)
var TURRET_LASER_BULLET_DAMAGE = 1
var TURRET_LASER_BULLET_DAMAGE_COST = 500
var TURRET_LASER_BULLET_EXPLOSION_COLOR = Color(0, 2, 0)

var TURRET_LASER_BULLET_RADIUS = 8
var TURRET_LASER_BULLET_SPEED = 400		# Pixels per second
var TURRET_LASER_BULLET_SPEED_COST = 250		# Pixels per second
var TURRET_LASER_BURST_SIZE = 1			# Bullets per attack
var TURRET_LASER_COOLDOWN = 2			# Seconds
var TURRET_LASER_COOLDOWN_COST = 1000
var TURRET_LASER_INACCURACY = 20		# Max number of pixels target can be off (both x and y)

var TURRET_MISSILE_BULLET_DAMAGE = 2
var TURRET_MISSILE_EXPLOSION_DAMAGE = 4

# Basic Enemy Data
var ENEMY_BASIC_DAMAGE = 1
var ENEMY_BASIC_HP = 1
var ENEMY_BASIC_RADIUS = 16
var ENEMY_BASIC_MOVEMENT_SPEED = 80
var ENEMY_BASIC_VALUE = 100

# Zigzag Enemy Data
var ENEMY_ZIGZAG_DAMAGE = 1
var ENEMY_ZIGZAG_HP = 1
var ENEMY_ZIGZAG_RADIUS = 16
var ENEMY_ZIGZAG_MOVEMENT_SPEED = 80
var ENEMY_ZIGZAG_VALUE = 100
var ENEMY_ZIGZAG_TIMER = 2

# Splitting Enemy Data
var ENEMY_SPLITTER_DAMAGE = 1
var ENEMY_SPLITTER_HP = 1
var ENEMY_SPLITTER_RADIUS = 16
var ENEMY_SPLITTER_MOVEMENT_SPEED = 80
var ENEMY_SPLITTER_VALUE = 100
var ENEMY_SPLITTER_COUNT = 1
var ENEMY_SPLITTER_TIMER = 5

# ASTEROID Enemy Data
var ENEMY_ASTEROID_DAMAGE = 5
var ENEMY_ASTEROID_HP = 10
var ENEMY_ASTEROID_RADIUS = 32
var ENEMY_ASTEROID_MOVEMENT_SPEED = 35
var ENEMY_ASTEROID_VALUE = 250

# AWESOME Enemy Data
var AWESOME_ENEMY_SPLITTER_COUNT = 3
var ENEMY_AWESOME_DAMAGE = -1
var AWESOME_NUMBER = 26
var ENEMY_AWESOME_VALUE = 3000

# Upgrade information
var UPGRADE_INCREMENT_PLAYER_BULLET_EXPLOSION_DAMAGE = 2
var UPGRADE_COST_PLAYER_BULLET_EXPLOSION_DAMAGE = 50
var UPGRADE_INCREMENT_PLAYER_BULLET_EXPLOSION_SIZE = .25
var UPGRADE_COST_PLAYER_BULLET_EXPLOSION_SIZE = 50
var UPGRADE_INCREMENT_PLAYER_BULLET_SPEED = 25
var UPGRADE_COST_PLAYER_BULLET_SPEED = 50

func reset():
	# Player Turret Data
	PLAYER_BULLET_EXPLOSION_DAMAGE = 2
	PLAYER_BULLET_EXPLOSION_DAMAGE_COST = 500
	PLAYER_BULLET_EXPLOSION_SIZE = 1.5	# Maximum times larger than original explosion can be
	PLAYER_BULLET_EXPLOSION_SIZE_COST = 1000	# Maximum times larger than original explosion can be
	PLAYER_BULLET_SPEED = 1000			# Pixels per second
	PLAYER_BULLET_COLOR = Color(2, 2, 2)
	PLAYER_MAX_HP = 20
	PLAYER_MAX_HP_COST = 200
	
	# Laser Turret Data
	TURRET_LASER_COUNT = 0
	TURRET_LASER_COUNT_COST = 2000
	TURRET_LASER_BULLET_COLOR = Color(0, 1.3, 0)
	TURRET_LASER_BULLET_DAMAGE = 1
	TURRET_LASER_BULLET_DAMAGE_COST = 500
	TURRET_LASER_BULLET_EXPLOSION_COLOR = Color(0, 2, 0)
	
	TURRET_LASER_BULLET_RADIUS = 8
	TURRET_LASER_BULLET_SPEED = 400		# Pixels per second
	TURRET_LASER_BULLET_SPEED_COST = 250		# Pixels per second
	TURRET_LASER_BURST_SIZE = 1			# Bullets per attack
	TURRET_LASER_COOLDOWN = 2			# Seconds
	TURRET_LASER_COOLDOWN_COST = 1000
	TURRET_LASER_INACCURACY = 20		# Max number of pixels target can be off (both x and y)
	
	TURRET_MISSILE_BULLET_DAMAGE = 2
	TURRET_MISSILE_EXPLOSION_DAMAGE = 4
	
	# Basic Enemy Data
	ENEMY_BASIC_DAMAGE = 1
	ENEMY_BASIC_HP = 1
	ENEMY_BASIC_RADIUS = 16
	ENEMY_BASIC_MOVEMENT_SPEED = 80
	ENEMY_BASIC_VALUE = 100
	
	# Zigzag Enemy Data
	ENEMY_ZIGZAG_DAMAGE = 1
	ENEMY_ZIGZAG_HP = 1
	ENEMY_ZIGZAG_RADIUS = 16
	ENEMY_ZIGZAG_MOVEMENT_SPEED = 80
	ENEMY_ZIGZAG_VALUE = 100
	ENEMY_ZIGZAG_TIMER = 2
	
	# Splitting Enemy Data
	ENEMY_SPLITTER_DAMAGE = 1
	ENEMY_SPLITTER_HP = 1
	ENEMY_SPLITTER_RADIUS = 16
	ENEMY_SPLITTER_MOVEMENT_SPEED = 80
	ENEMY_SPLITTER_VALUE = 100
	ENEMY_SPLITTER_COUNT = 1
	ENEMY_SPLITTER_TIMER = 5
	
	# ASTEROID Enemy Data
	ENEMY_ASTEROID_DAMAGE = 5
	ENEMY_ASTEROID_HP = 10
	ENEMY_ASTEROID_RADIUS = 32
	ENEMY_ASTEROID_MOVEMENT_SPEED = 35
	ENEMY_ASTEROID_VALUE = 250
	
	# Upgrade information
	UPGRADE_INCREMENT_PLAYER_BULLET_EXPLOSION_DAMAGE = 2
	UPGRADE_COST_PLAYER_BULLET_EXPLOSION_DAMAGE = 50
	UPGRADE_INCREMENT_PLAYER_BULLET_EXPLOSION_SIZE = .25
	UPGRADE_COST_PLAYER_BULLET_EXPLOSION_SIZE = 50
	UPGRADE_INCREMENT_PLAYER_BULLET_SPEED = 25
	UPGRADE_COST_PLAYER_BULLET_SPEED = 50
